#ifndef ENGINE_CLIENT_INFCLASS_H
#define ENGINE_CLIENT_INFCLASS_H

#define INFCLASS_CLIENT_VERSION 171

#define INFC_UPDATES_URL "https://infclass.github.io/files"

#endif // ENGINE_CLIENT_INFCLASS_H
